### ISSUE TITLE
Question regarding benchmarking the MCS score.

### ISSUE THREAD

**Issue by chirag-agarwall** [google-research-datasets/bim#3]
Dear @sherryy,

Thank you so much for releasing this great benchmark for the interpretability community!
It is so awesome that I am already using it in my current work! :)

I ran your MCS metric for 10k images using the Vanilla Gradient method and I get a score of **0.1303**. However, as per Figure 5 in your [arXiv](https://arxiv.org/pdf/1907.09701.pdf) paper, it seems the score is **~0.15**. 

Could you help me verify the exact MCS number for Vanilla Gradient?

It is critical for me to be able to reproduce your numbers.
I have been staring at this for a week but still could not figure out what is going wrong.

Your help is greatly appreciated! :)
Chirag

**Comment by sherryy** [comment]
Hi Chirag,

Thank you for your inquiry. Note that the **exact** dataset evaluate in the paper can be different from running scripts/construct_bam_dataset.py due to the randomness in where the objects are pasted. Due to copyright issues, we can only provide scripts for constructing the BAM dataset from COCO and MiniPlaces, rather than directly releasing the **exact** dataset evaluated in the paper. However, the result should be similar.

In our most recent version of the paper (https://arxiv.org/abs/1907.09701), we added standard deviations to the measurements (such as those in Figure 4). Hope this is helpful.
